config/routes.rb
Myapp::Application.routes.draw do
  get "welcome/index"
  get "home/index"

root to: 'welcome#index'

  resources :trips, :creditcards, :rates, :results

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  #has_and_belongs_to_many :rates
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    @trips = Trip.all
  end
  
  def show
    @trip = Trip.find(params[:id])
  end
  
  def new
    @trip = Trip.new
  end
  
  def edit
    @trip = Trip.find(params[:id])
  end
  
  def create
    @trip = Trip.create(trip_check) #bleh
    
    if @trip.save
      redirect_to @trip
    else
      render 'new'
    end
    
  end
  
  def update 
    @trip = Trip.find(params[:id])
    
    if @trip.update(trip_check)
      redirect_to @trip
    else
      render 'edit'
    end
    
  end
  
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    
    redirect_to trips_path
  end
  
  private
    #require all new entries to have these four fields, at a minimum, INCLUDING notes
    def trip_check
      params.require(:trip).permit(:name,
                                   :costinusd,
                                   :aacostpts,
                                   :aacostusd,
                                   :bacostpts,
                                   :bacostusd,
                                   :uacostpts,
                                   :uacostusd,
                                   :dlcostpts,
                                   :dlcostusd,
                                   :ascostpts,
                                   :ascostusd,
                                   :nkcostpts,
                                   :nkcostusd,
                                   :sqcostpts,
                                   :sqcostusd,
                                   :lacostpts,
                                   :lacostusd,
                                   :accostpts,
                                   :accostusd)
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_for @trip do |t| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@trip.errors.count, "error") %> prohibited this credit card from being saved:
      </h2>
      <ul>
        <% @trip.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <form role="form">
  
  <div class="form-group">
  <%= t.label :name %></br>
  <%= t.text_field :name %>
  </div>
  
  <div class="form-group">
  <%= t.label :"Cost in USD" %></br>
  <%= t.number_field :costinusd %>
  </div>
  
  <!-- AA -->
  <div class="form-group">
  <p>
  <%= t.label :'American points cost' %></br>
  <%= t.number_field :aacostpts %>
  </p>
  
  <p>
  <%= t.label :'American USD copay' %></br>
  <%= t.number_field :aacostusd %>
  </p>
  </div>
  
  <!-- BA -->
  <div class="form-group">
  <div class="form-group">
  <p>
  <%= t.label :'BA Avios cost' %></br>
  <%= t.number_field :bacostpts %>
  </p>
  </div>
  
  <div class="form-group">
  <p>
  <%= t.label :'BA USD copay' %></br>
  <%= t.number_field :bacostusd %>
  </p>
  </div>
  </div>
  
  <!-- UA -->
  <p>
  <%= t.label :'United points cost' %></br>
  <%= t.number_field :uacostpts %>
  </p>
  
  <p>
  <%= t.label :'United USD copay' %></br>
  <%= t.number_field :uacostusd %>
  </p>
  
  <!-- DL -->
  <p>
  <%= t.label :'Delta points cost' %></br>
  <%= t.number_field :dlcostpts %>
  </p>
  
  <p>
  <%= t.label :'Delta USD copay' %></br>
  <%= t.number_field :dlcostusd %>
  </p>
  
  <!-- AS -->
  <p>
  <%= t.label :'Alaska points cost' %></br>
  <%= t.number_field :ascostpts %>
  </p>
  
  <p>
  <%= t.label :'Alaska USD copay' %></br>
  <%= t.number_field :ascostusd %>
  </p>
  
  <!-- NK -->
  <p>
  <%= t.label :'Spirit points cost' %></br>
  <%= t.number_field :nkcostpts %>
  </p>
  
  <p>
  <%= t.label :'Spirit USD copay' %></br>
  <%= t.number_field :nkcostusd %>
  </p>
  
  <!-- SQ -->
  <p>
  <%= t.label :'Singapore points cost' %></br>
  <%= t.number_field :sqcostpts %>
  </p>
  
  <p>
  <%= t.label :'Singapore USD copay' %></br>
  <%= t.number_field :sqcostusd %>
  </p>
  
  <!-- LA -->
  <p>
  <%= t.label :'LAN points cost' %></br>
  <%= t.number_field :lacostpts %>
  </p>
  
  <p>
  <%= t.label :'LAN USD copay' %></br>
  <%= t.number_field :lacostusd %>
  </p>
  
  <!-- AC -->
  <p>
  <%= t.label :'Aeroplan points cost' %></br>
  <%= t.number_field :accostpts %>
  </p>
  
  <p>
  <%= t.label :'Aeroplan USD copay' %></br>
  <%= t.number_field :accostusd %>
  </p>
  
  <!-- CX -->
  <p>
  <%= t.label :'Cathay Pacific points cost' %></br>
  <%= t.number_field :cxcostpts %>
  </p>

  <p>
  <%= t.label :'Cathay Pacific USD copay' %></br>
  <%= t.number_field :cxcostusd %>
  </p>
  
  <!-- BR -->
  <p>
  <%= t.label :'EVA points cost' %></br>
  <%= t.number_field :brcostpts %>
  </p>

  <p>
  <%= t.label :'EVA USD copay' %></br>
  <%= t.number_field :brcostusd %>
  </p>
  
  <!-- EY -->
  <p>
  <%= t.label :'Etihad points cost' %></br>
  <%= t.number_field :eycostpts %>
  </p>

  <p>
  <%= t.label :'Etihad USD copay' %></br>
  <%= t.number_field :eycostusd %>
  </p>
  
  <!-- AF -->
  <p>
  <%= t.label :'Flying Blue points cost' %></br>
  <%= t.number_field :afcostpts %>
  </p>

  <p>
  <%= t.label :'Flying Blue USD copay' %></br>
  <%= t.number_field :afcostusd %>
  </p>
  
  <!-- GA -->
  <p>
  <%= t.label :'Garuda Indonesia points cost' %></br>
  <%= t.number_field :gacostpts %>
  </p>

  <p>
  <%= t.label :'Garuda Indonesia USD copay' %></br>
  <%= t.number_field :gacostusd %>
  </p>
  
  <!-- MH -->
  <p>
  <%= t.label :'Malaysia Air points cost' %></br>
  <%= t.number_field :mhcostpts %>
  </p>

  <p>
  <%= t.label :'Malaysia Air USD copay' %></br>
  <%= t.number_field :mhcostusd %>
  </p>
  
  <!-- QF -->
  <p>
  <%= t.label :'Qantas points cost' %></br>
  <%= t.number_field :qfcostpts %>
  </p>

  <p>
  <%= t.label :'Qantas USD copay' %></br>
  <%= t.number_field :qfcostusd %>
  </p>
  
  <!-- QR -->
  <p>
  <%= t.label :'Qatar points cost' %></br>
  <%= t.number_field :qrcostpts %>
  </p>

  <p>
  <%= t.label :'Qatar USD copay' %></br>
  <%= t.number_field :qrcostusd %>
  </p>
  
  <!-- TG -->
  <p>
  <%= t.label :'Thai Airways points cost' %></br>
  <%= t.number_field :tgcostpts %>
  </p>

  <p>
  <%= t.label :'Thai USD copay' %></br>
  <%= t.number_field :tgcostusd %>
  </p>
  
  <!-- VS -->
  <p>
  <%= t.label :'Virgin Atlantic points cost' %></br>
  <%= t.number_field :vscostpts %>
  </p>

  <p>
  <%= t.label :'Virgin Atlantic USD copay' %></br>
  <%= t.number_field :vscostusd %>
  </p>
  
  <!-- AZ -->
  <p>
  <%= t.label :'Alitalia points cost' %></br>
  <%= t.number_field :azcostpts %>
  </p>

  <p>
  <%= t.label :'Alitalia USD copay' %></br>
  <%= t.number_field :azcostusd %>
  </p>
  
  <!-- NH -->
  <p>
  <%= t.label :'ANA points cost' %></br>
  <%= t.number_field :nhcostpts %>
  </p>

  <p>
  <%= t.label :'ANA USD copay' %></br>
  <%= t.number_field :nhcostusd %>
  </p>
  
  <!-- AM -->
  <p>
  <%= t.label :'AeroMexico points cost' %></br>
  <%= t.number_field :amcostpts %>
  </p>

  <p>
  <%= t.label :'AeroMexico USD copay' %></br>
  <%= t.number_field :amcostusd %>
  </p>
  
  <!-- LY -->
  <p>
  <%= t.label :'El Al points cost' %></br>
  <%= t.number_field :lycostpts %>
  </p>

  <p>
  <%= t.label :'El Al USD copay' %></br>
  <%= t.number_field :lycostusd %>
  </p>
  
  <!-- HA -->
  <p>
  <%= t.label :'Hawaiian points cost' %></br>
  <%= t.number_field :hacostpts %>
  </p>

  <p>
  <%= t.label :'Hawaiian USD copay' %></br>
  <%= t.number_field :hacostusd %>
  </p>
  
  <!-- IB -->
  <p>
  <%= t.label :'Iberia points cost' %></br>
  <%= t.number_field :ibcostpts %>
  </p>

  <p>
  <%= t.label :'Iberia USD copay' %></br>
  <%= t.number_field :ibcostusd %>
  </p>
  
  <!-- VX -->
  <p>
  <%= t.label :'Virgin America points cost' %></br>
  <%= t.number_field :vxcostpts %>
  </p>

  <p>
  <%= t.label :'Virgin America USD copay' %></br>
  <%= t.number_field :vxcostusd %>
  </p>
  
  <!-- AB -->
  <p>
  <%= t.label :'Air Berlin points cost' %></br>
  <%= t.number_field :abcostpts %>
  </p>

  <p>
  <%= t.label :'Air Berline USD copay' %></br>
  <%= t.number_field :abcostusd %>
  </p>
  
  <!-- CA -->
  <p>
  <%= t.label :'Air China points cost' %></br>
  <%= t.number_field :cacostpts %>
  </p>

  <p>
  <%= t.label :'Air China USD copay' %></br>
  <%= t.number_field :cacostusd %>
  </p>
  
  <!-- NZ -->
  <p>
  <%= t.label :'Air New Zealand points cost' %></br>
  <%= t.number_field :nzcostpts %>
  </p>

  <p>
  <%= t.label :'Air New Zealand USD copay' %></br>
  <%= t.number_field :nzcostusd %>
  </p>
  
  <!-- OZ -->
  <p>
  <%= t.label :'Asiana points cost' %></br>
  <%= t.number_field :ozcostpts %>
  </p>

  <p>
  <%= t.label :'Asiana USD copay' %></br>
  <%= t.number_field :ozcostusd %>
  </p>
  
  <!-- MU -->
  <p>
  <%= t.label :'China Eastern points cost' %></br>
  <%= t.number_field :mucostpts %>
  </p>

  <p>
  <%= t.label :'China Eastern USD copay' %></br>
  <%= t.number_field :mucostusd %>
  </p>
  
  <!-- CZ -->
  <p>
  <%= t.label :'China Southern points cost' %></br>
  <%= t.number_field :czcostpts %>
  </p>

  <p>
  <%= t.label :'China Southern USD copay' %></br>
  <%= t.number_field :czcostusd %>
  </p>
  
  <!-- EK -->
  <p>
  <%= t.label :'Emirates points cost' %></br>
  <%= t.number_field :ekcostpts %>
  </p>

  <p>
  <%= t.label :'Emirates USD copay' %></br>
  <%= t.number_field :ekcostusd %>
  </p>
  
  <!-- G3 -->
  <p>
  <%= t.label :'Gol points cost' %></br>
  <%= t.number_field :g3costpts %>
  </p>

  <p>
  <%= t.label :'Gol USD copay' %></br>
  <%= t.number_field :g3costusd %>
  </p>
  
  <!-- HU -->
  <p>
  <%= t.label :'Hainan points cost' %></br>
  <%= t.number_field :hucostpts %>
  </p>

  <p>
  <%= t.label :'Hainan USD copay' %></br>
  <%= t.number_field :hucostusd %>
  </p>
  
  <!-- JL -->
  <p>
  <%= t.label :'JAL points cost' %></br>
  <%= t.number_field :jlcostpts %>
  </p>

  <p>
  <%= t.label :'JAL USD copay' %></br>
  <%= t.number_field :jlcostusd %>
  </p>
  
  <!-- LH -->
  <p>
  <%= t.label :'Lufthansa points cost' %></br>
  <%= t.number_field :lhcostpts %>
  </p>

  <p>
  <%= t.label :'Lufthansa USD copay' %></br>
  <%= t.number_field :lhcostusd %>
  </p>
  
  <!-- SV -->
  <p>
  <%= t.label :'Saudia points cost' %></br>
  <%= t.number_field :svcostpts %>
  </p>

  <p>
  <%= t.label :'Saudia USD copay' %></br>
  <%= t.number_field :svcostusd %>
  </p>
  
  <!-- VA -->
  <p>
  <%= t.label :'Virgin Australia points cost' %></br>
  <%= t.number_field :vacostpts %>
  </p>

  <p>
  <%= t.label :'Virgin Australia USD copay' %></br>
  <%= t.number_field :vacostusd %>
  </p>
  
  <p>
  <%= t.submit %>
  </p>
  
  </form>
  
<% end %>

app/views/trips/edit.html.erb
<h1>Tralue - Editing trip</h1>

<%= form_for :trip, url: trip_path(@trip), method: :patch do |t| %>

    <% if @trip.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@trip.errors.count, "error") %> prevented this credit card from being updated:
            </h2>
            <ul>
                <% @trip.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <%= render 'form' %>
    
<% end %>

<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<h1>Tralue - Listing trips</h1>

<div class="table-responsive">
<table class="table table-hover">
    <tr>
        <th>Name</th>
        <th>Cost in USD</th>
        <th>AA cost in points</th>
        <th>AA cost in USD</th>
        <th>BA pts</th>
        <th>BA USD</th>
        <th>UA pts</th>
        <th>UA USD</th>
        <th>DL pts</th>
        <th>DL USD</th>
        <th>AS pts</th>
        <th>AS USD</th>
        <th>NK pts</th>
        <th>NK USD</th>
        <th>SQ pts</th>
        <th>SQ USD</th>
    </tr>
    
    <% @trips.each do |t| %>
        <tr>
            <td><%= t.name %></td>
            <td>$<%= t.costinusd %></td>
            <td><%= t.aacostpts %></td>
            <td>$<%= t.aacostusd %></td>
            <td><%= t.bacostpts %></td>
            <td>$<%= t.bacostusd %></td>
            <td><%= t.uacostpts %></td>
            <td>$<%= t.uacostusd %></td>
            <td><%= t.dlcostpts %></td>
            <td>$<%= t.dlcostusd %></td>
            <td><%= t.ascostpts %></td>
            <td>$<%= t.ascostusd %></td>
            <td><%= t.nkcostpts %></td>
            <td>$<%= t.nkcostusd %></td>
            <td><%= t.sqcostpts %></td>
            <td>$<%= t.sqcostusd %></td>

            <td><%= link_to 'Show', trip_path(t), class: 'btn btn-primary' %></td>
            <td><%= link_to 'Edit', edit_trip_path(t), class: 'btn btn-primary' %></td>
            <td><%= link_to 'Destroy', trip_path(t), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %></td>
            <td><%= link_to 'View recommendations', result_path(t), class: 'btn btn-success' %></td>
        </tr>
    <% end %>
</table>
</div>
<%= link_to 'Home', root_path, class: 'btn btn-primary' %>
<%= link_to 'New trip', new_trip_path, class: 'btn btn-primary' %>

app/views/trips/new.html.erb
<h1>New trip</h1>

<%= form_for :trip, url: trips_path do |tr| %>

  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@trip.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @trip.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'form' %>
  

  
<% end %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<h1>Tralue - Display trip</h1>

<%= form_for :trip, url: trip_path(@trip), method: :get do |t| %>

    <% if @trip.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@trip.errors.count, "error") %> prevented this credit card from being updated:
            </h2>
            <ul>
                <% @trip.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <%= render 'form' %>
  
<% end %>

<%= link_to 'Back', trips_path, class: 'btn btn-primary' %>
<%= link_to 'Edit', edit_trip_path(@trip), class: 'btn btn-primary' %>
<%= link_to 'Recommendations', result_path(@trip), class: 'btn btn-primary' %>