config/routes.rb
Myapp::Application.routes.draw do
  get "welcome/index"
  get "home/index"

root to: 'welcome#index'

  resources :trips, :creditcards, :rates, :results

end

app/models/result.rb
class Result
  include ActiveModel::Model
  
  attr_accessor :name, :costinusd, :issuer, :points_program, :spend_bonus,
                       :aacostpts,
                       :aacostusd,
                       :bacostpts,
                       :bacostusd,
                       :uacostpts,
                       :uacostusd,
                       :dlcostpts,
                       :dlcostusd,
                       :ascostpts,
                       :ascostusd,
                       :nkcostpts,
                       :nkcostusd,
                       :sqcostpts,
                       :sqcostusd,
                       :lacostpts,
                       :lacostusd,
                       :accostpts,
                       :accostusd,
                       :cxcostpts,
                       :cxcostusd,
                       :brcostpts,
                       :brcostusd,
                       :eycostpts,
                       :eycostusd,
                       :afcostpts,
                       :afcostusd,
                       :gacostpts,
                       :gacostusd,
                       :mhcostpts,
                       :mhcostusd,
                       :qfcostpts,
                       :qfcostusd,
                       :qrcostpts,
                       :qrcostusd,
                       :tgcostpts,
                       :tgcostusd,
                       :vscostpts,
                       :vscostusd,
                       :azcostpts,
                       :azcostusd,
                       :nhcostpts,
                       :nhcostusd,
                       :amcostpts,
                       :amcostusd,
                       :lycostpts,
                       :lycostusd,
                       :hacostpts,
                       :hacostusd,
                       :ibcostpts,
                       :ibcostusd,
                       :vxcostpts,
                       :vxcostusd,
                       :abcostpts,
                       :abcostusd,
                       :cacostpts,
                       :cacostusd,
                       :nzcostpts,
                       :nzcostusd,
                       :ozcostpts,
                       :ozcostusd,
                       :mucostpts,
                       :mucostusd,
                       :czcostpts,
                       :czcostusd,
                       :ekcostpts,
                       :ekcostusd,
                       :g3costpts,
                       :g3costusd,
                       :hucostpts,
                       :hucostusd,
                       :jlcostpts,
                       :jlcostusd,
                       :lhcostpts,
                       :lhcostusd,
                       :svcostpts,
                       :svcostusd,
                       :vacostpts,
                       :vacostusd
                       
  attr_accessor :arrayofcards, :percentage
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  http_basic_authenticate_with name: "shunter", password: "derpderp", except: [:show]
  
  class Resulta
    include ActiveModel::Model
    
    attr_reader :name, :costinusd
    attr_writer :name, :costinusd
  end
  
  def index
    @results = []
    
    costs = Trip.all
    
    costs.each do |cost|
      @results.insert(0, cost)
    end
    
    #@result.name = "Bob"
  end
  
  def show
    #@trip = Trip.find(params[:id])
    
    costs = Trip.find(params[:id])
    @result = Result.new
    @result.name = costs.name
    @result.costinusd = costs.costinusd
    @result.aacostpts = costs.aacostpts
    @result.aacostusd = costs.aacostusd
    @result.bacostpts = costs.bacostpts
    @result.bacostusd = costs.bacostusd
    @result.uacostpts = costs.uacostpts
    @result.uacostusd = costs.uacostusd
    @result.dlcostpts = costs.dlcostpts
    @result.dlcostusd = costs.dlcostusd
    @result.ascostpts = costs.ascostpts
    @result.ascostusd = costs.ascostusd
    @result.nkcostpts = costs.nkcostpts
    @result.nkcostusd = costs.nkcostusd
    @result.sqcostpts = costs.sqcostpts
    @result.sqcostusd = costs.sqcostusd
    @result.lacostpts = costs.lacostpts
    @result.lacostusd = costs.lacostusd
    @result.accostpts = costs.accostpts
    @result.accostusd = costs.accostusd
    @result.cxcostpts = costs.cxcostpts
    @result.cxcostusd = costs.cxcostusd
    @result.brcostpts = costs.brcostpts
    @result.brcostusd = costs.brcostusd
    @result.eycostpts = costs.eycostpts
    @result.eycostusd = costs.eycostusd
    @result.afcostpts = costs.afcostpts
    @result.afcostusd = costs.afcostusd
    @result.gacostpts = costs.gacostpts
    @result.gacostusd = costs.gacostusd
    @result.mhcostpts = costs.mhcostpts
    @result.mhcostusd = costs.mhcostusd
    @result.qfcostpts = costs.qfcostpts
    @result.qfcostusd = costs.qfcostusd
    @result.qrcostpts = costs.qrcostpts
    @result.qrcostusd = costs.qrcostusd
    @result.tgcostpts = costs.tgcostpts
    @result.tgcostusd = costs.tgcostusd
    @result.vscostpts = costs.vscostpts
    @result.vscostusd = costs.vscostusd
    @result.azcostpts = costs.azcostpts
    @result.azcostusd = costs.azcostusd
    @result.nhcostpts = costs.nhcostpts
    @result.nhcostusd = costs.nhcostusd
    @result.amcostpts = costs.amcostpts
    @result.amcostusd = costs.amcostusd
    @result.lycostpts = costs.lycostpts
    @result.lycostusd = costs.lycostusd
    @result.hacostpts = costs.hacostpts
    @result.hacostusd = costs.hacostusd
    @result.ibcostpts = costs.ibcostpts
    @result.ibcostusd = costs.ibcostusd
    @result.vxcostpts = costs.vxcostpts
    @result.vxcostusd = costs.vxcostusd
    @result.abcostpts = costs.abcostpts
    @result.abcostusd = costs.abcostusd
    @result.cacostpts = costs.cacostpts
    @result.cacostusd = costs.cacostusd
    @result.nzcostpts = costs.nzcostpts
    @result.nzcostusd = costs.nzcostusd
    @result.ozcostpts = costs.ozcostpts
    @result.ozcostusd = costs.ozcostusd
    @result.mucostpts = costs.mucostpts
    @result.mucostusd = costs.mucostusd
    @result.czcostpts = costs.czcostpts
    @result.czcostusd = costs.czcostusd
    @result.ekcostpts = costs.ekcostpts
    @result.ekcostusd = costs.ekcostusd
    @result.g3costpts = costs.g3costpts
    @result.g3costusd = costs.g3costusd
    @result.hucostpts = costs.hucostpts
    @result.hucostusd = costs.hucostusd
    @result.jlcostpts = costs.jlcostpts
    @result.jlcostusd = costs.jlcostusd
    @result.lhcostpts = costs.lhcostpts
    @result.lhcostusd = costs.lhcostusd
    @result.svcostpts = costs.svcostpts
    @result.svcostusd = costs.svcostusd
    @result.vacostpts = costs.vacostpts
    @result.vacostusd = costs.vacostusd
    
    #puts costs.aacostpts
    
    cards = Creditcard.all
    #cards = Creditcard.find(params[:id])
    
    #cards.each do |cc|
    #@result.name = cc.name
    #@result.issuer = cc.issuer
    #@result.points_program = cc.points_program
    #@result.spend_bonus = cc.spend_bonus
    #end
    
    costs = Trip.find(params[:id])
    rates = Rate.all
    cards = Creditcard.all
    
    #debug_string = ""
    @debug_string = ""
    @result.arrayofcards = []
    
    rates.each do |rate|
      cards.each do |card|
        @debug_string << card.name
        if card.points_program == rate.transferringprogram
          #@result.name << card.points_program + " = " + rate.transferringprogram
          if @result.arrayofcards == nil
            @result.arrayofcards = []
            #debug_string = "Empty. "
          end
          
          #debug_string = "Adding card."
          #@debug_string = card.name
          temparray = []
          
          case rate.transfereeprogram
          when "american"
            if @result.aacostpts.nil?
              percentage = 0
              #debug_string = "Percentage to 0."
              @debug_string << " nil."
            else
              percentage = ((card.first_purchase_bonus + card.spend_bonus + card.spend_requirement) * rate.transferratio) / @result.aacostpts * 100
            end
            
            miles_required = @result.aacostpts
            if @result.aacostusd.nil?
              copay = 0
            else
              copay = @result.aacostusd
            end
            
            temparray = [card, rate, "American", percentage, miles_required, copay]
            #debug_string = "american"
            if percentage > 0
              @result.arrayofcards.push(temparray)
            end
          when "ba"
            if @result.bacostpts.nil?
              percentage = 0
            else
              percentage = ((card.first_purchase_bonus + card.spend_bonus + card.spend_requirement) * rate.transferratio) / @result.bacostpts * 100
            end
            
            miles_required = @result.bacostpts
            if @result.bacostusd.nil?
              copay = 0
            else
              copay = @result.bacostusd
            end
            
            temparray = [card, rate, "BA", percentage, miles_required, copay]
            #debug_string = "ba"
            if percentage > 0
              @result.arrayofcards.push(temparray)
            end
          when "united"
            if @result.uacostpts.nil?
              percentage = 0
            else
              percentage = ((card.first_purchase_bonus + card.spend_bonus + card.spend_requirement) * rate.transferratio) / @result.uacostpts * 100
            end
            
            miles_required = @result.uacostpts
            if @result.uacostusd.nil?
              copay = 0
            else
              copay = @result.uacostusd
            end
            
            temparray = [card, rate, "United", percentage, miles_required, copay]
            #debug_string = "united"
            if percentage > 0
              @result.arrayofcards.push(temparray)
            end
          when "delta"
            if @result.dlcostpts.nil?
              percentage = 0
              @result.name << "Delta cost is nil."
            else
              percentage = ((card.first_purchase_bonus + card.spend_bonus + card.spend_requirement) * rate.transferratio) / @result.dlcostpts * 100
            end
            
            miles_required = @result.dlcostpts
            if @result.dlcostusd.nil?
              copay = 0
            else
              copay = @result.dlcostusd
            end
            
            temparray = [card, rate, "Delta", percentage, miles_required, copay]
            #debug_string = "dl"
            if percentage > 0
              @result.arrayofcards.push(temparray)
            end
          when "alaska"
            if @result.ascostpts.nil?
              percentage = 0
            else
              percentage = ((card.first_purchase_bonus + card.spend_bonus + card.spend_requirement) * rate.transferratio) / @result.ascostpts * 100
            end
            
            miles_required = @result.ascostpts
            if @result.ascostusd.nil?
              copay = 0
            else
              copay = @result.ascostusd
            end
            
            temparray = [card, rate, "Alaska", percentage, miles_required, copay]
            #debug_string = "as"
            if percentage > 0
              @result.arrayofcards.push(temparray)
            end
          when "spirit"
            if @result.nkcostpts.nil?
              percentage = 0
            else
              percentage = ((card.first_purchase_bonus + card.spend_bonus + card.spend_requirement) * rate.transferratio) / @result.nkcostpts * 100
            end
            
            miles_required = @result.nkcostpts
            if @result.nkcostusd.nil?
              copay = 0
            else
              copay = @result.nkcostusd
            end
            
            temparray = [card, rate, "Spirit", percentage, miles_required, copay]
            #debug_string = "nk"
            if percentage > 0
              @result.arrayofcards.push(temparray)
            end
          when "singapore"
            if @result.sqcostpts.nil?
              percentage = 0
              @debug_string << " Singapore nil."
            else
              percentage = ((card.first_purchase_bonus + card.spend_bonus + card.spend_requirement) * rate.transferratio) / @result.sqcostpts * 100
            end
            
            miles_required = @result.sqcostpts
            if @result.sqcostusd.nil?
              copay = 0
            else
              copay = @result.sqcostusd
            end
            
            temparray = [card, rate, "Singapore", percentage, miles_required, copay]
            #debug_string = "sq"
            if percentage > 0
              @result.arrayofcards.push(temparray)
            end
          when "lan"
            if @result.lacostpts.nil?
              percentage = 0
            else

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/broken_form.html.erb
<%= form_for @result do |t| %>
  
  <p>
  <%= t.label :name %></br>
  <%= t.text_field :name %>
  </p>
  
  <p>
  <%= t.label :issuer %></br>
  <%= t.text_field :issuer %>
  </p>
  
  <p>
  <%= t.label :'Cost in USD' %></br>
  <%= t.number_field :costinusd %>
  </p>
  
  <p>
  <%= t.label :'Points program' %></br>
  <%= t.text_field :points_program %>
  </p>
  
  <p>
  <%= t.label :'Spend bonus' %></br>
  <%= t.number_field :spend_bonus %>
  </p>
  
  <p>
  <%= t.label :'Percentage of points required' %></br>
  <%= t.number_field :percentage %>
  </p>
  

  
  <p>
  <%= t.submit %>
  </p>
  
<% end %>

app/views/results/index.html.erb
<h1>Listing results</h1>

<table>
    <tr>
        <th>Name</th>
        <th>Cost in USD</th>
        <th>AA cost in points</th>
        <th>AA cost in USD</th>
        <th>BA pts</th>
        <th>BA USD</th>
        <th>UA pts</th>
        <th>UA USD</th>
        <th>DL pts</th>
        <th>DL USD</th>
        <th>AS pts</th>
        <th>AS USD</th>
        <th>NK pts</th>
        <th>NK USD</th>
        <th>SQ pts</th>
        <th>SQ USD</th>
        <th>LA pts</th>
        <th>LA USD</th>
        <th>AC pts</th>
        <th>AC USD</th>
    </tr>
    <tr>
        <% @result.arrayofcards.each do |a| %>
            <li><%= a[0].name + a[3] %></li>
        <% end %>
    </tr>
    
    <% @results.each do |t| %>
        <tr>
            <td><%= t.name %></td>
            <td><%= t.costinusd %></td>
 
            <td><%= link_to 'Show', result_path(t) %></td>
            <td><%= link_to 'Edit', edit_result_path(t) %></td>
            <td><%= link_to 'Destroy', result_path(t), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
</table>

app/views/results/show.html.erb
<h1>Tralue - Credit card recommendations for <%= @result.name %></h1>

<table class="table table-hover">
    <tr>
        <th>Name</th>
        <th>By</th>
        <th>Percent of points required for trip provided by this card</th>
        <!-- % -->
        <th>Airline issuing ticket</th>
        <th>Points cost</th>
        <th>Cash copay</th>
        <th>Points to be earned</th>
        <!-- (first purchase bonus + spend bonus + spend requirement * points per dollar) * transfer ratio -->
        <th>Transfer notes</th>
        <th>Credit card notes</th>
        <th>Annual fee</th>
        <th>Waived first year?</th>
        <th>Application</th>
        <th>Value of points</th>
        <th>CPM value</th>
        <!-- Total value of points for this redemption (cost of airfare - annual fee - copay) * percentage-->
        <!-- CPM value -->
    </tr>
    
    <% @result.arrayofcards.each do |a| %>
        <tr>
            <td><%= link_to a[0].name, creditcard_path(a) %></td>
            <td><%= a[0].issuer %></td>
            <td><%= sprintf("%.0f", a[3]) + "%" %></td>
            <td><%= a[2] %></td>
            <td><%= a[4] %></td>
            <td><%= "$" + sprintf("%.0f",a[5]) %></td>
            <td><%= sprintf("%.0f",(a[0].first_purchase_bonus + a[0].spend_bonus + a[0].spend_requirement) * a[1].transferratio) %></td>
            <td><%= a[1].transfernotes %></td>
            <td><%= a[0].notes %></td>
            <td><%= a[0].annual_fee %></td>
            <td><%= a[0].fee_waived_first_year.to_s %></td>
            <td><%= link_to a[0].url, class: 'btn btn-success' do %>
                Application
            <% end %></td>
            <td><%= sprintf("%.0f", (@result.costinusd - ( if a[0].fee_waived_first_year then 0 else a[0].annual_fee end ) - a[5]) * a[3] / 100) %></td>
            <td><%= sprintf("%.1f", (@result.costinusd - ( if a[0].fee_waived_first_year then 0 else a[0].annual_fee end ) - a[5]) * a[3] / 100 / (a[0].first_purchase_bonus + a[0].spend_bonus + a[0].spend_requirement) * a[1].transferratio * 100) %></td>
        </tr>
    <% end %>
    
</table>

<%= link_to 'Back', trips_path, class: 'btn btn-primary' %>
<%= link_to 'Home', root_path, class: 'btn btn-primary' %>