config/routes.rb
Myapp::Application.routes.draw do
  get "welcome/index"
  get "home/index"

root to: 'welcome#index'

  resources :trips, :creditcards, :rates, :results

end

app/models/creditcard.rb
class Creditcard < ActiveRecord::Base
  #has_and_belongs_to_many :rates
  
  validates :name, presence: true
  validates :issuer, presence: true
end

app/controllers/creditcards_controller.rb
class CreditcardsController < ApplicationController
  def index 
    @creditcards = Creditcard.all
  end
  
  def show 
    @creditcard = Creditcard.find(params[:id])
  end
  
  def new
    @creditcard = Creditcard.new
    #code
  end
  
  def edit
    @creditcard = Creditcard.find(params[:id])
    
  end
  
  def create
    @creditcard = Creditcard.new(check_creditcard_params)
    
    if @creditcard.save
      redirect_to @creditcard
    else
      render 'new'
    end
  end
  
  def update
    @creditcard = Creditcard.find(params[:id])
    
    if @creditcard.update(check_creditcard_params)
      redirect_to @creditcard
    else
      render 'edit'
    end
    
  end
  
  def destroy
    @creditcard = Creditcard.find(params[:id])
    @creditcard.destroy
    
    redirect_to creditcards_path
  end
  
  private
    def check_creditcard_params
      params.require(:creditcard).permit(:name,
                                         :issuer,
                                         :annual_fee,
                                         :fee_waived_first_year,
                                         :points_program,
                                         :spend_bonus,
                                         :spend_requirement,
                                         :time_to_reach_spend_in_months,
                                         :first_purchase_bonus,
                                         :second_year_spend_bonus,
                                         :second_year_spend_requirement,
                                         :second_year_time_to_reach_spend_in_months,
                                         :points_per_dollar_spend_general_spend,
                                         :foreign_transaction_fee,
                                         :chip,
                                         :notes,
                                         :business,
                                         :personal,
                                         :image_index,
                                         :url)
      #code
    end
end

app/helpers/creditcards_helper.rb
module CreditcardsHelper
end

app/views/creditcards/_form.html.erb
<%= form_for @creditcard do |cc| %>
  <% if @creditcard.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@creditcard.errors.count, "error") %> prohibited this credit card from being saved:
      </h2>
      <ul>
        <% @creditcard.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
  <%= cc.label :name %></br>
  <%= cc.text_field :name %>
  </p>
  
  <p>
  <%= cc.label :issuer %></br>
  <%= cc.text_field :issuer %>
  </p>
  
  <p>
  <%= cc.label :annual_fee %></br>
  <%= cc.number_field :annual_fee %>
  </p>
  
  <p>
  <%= cc.label :fee_waived_first_year %></br>
  <%= cc.text_field :fee_waived_first_year %>
  </p>
  
  <p>
  <%= cc.label :points_program %></br>
  <%= cc.text_field :points_program %>
  </p>
  
  <p>
  <%= cc.label :spend_bonus %></br>
  <%= cc.number_field :spend_bonus %>
  </p>
  
  <p>
  <%= cc.label :spend_requirement %></br>
  <%= cc.number_field :spend_requirement %>
  </p>
  
  <p>
  <%= cc.label :time_to_reach_spend_in_months %></br>
  <%= cc.number_field :time_to_reach_spend_in_months %>
  </p>
  
  <p>
  <%= cc.label :first_purchase_bonus %></br>
  <%= cc.number_field :first_purchase_bonus %>
  </p>
  
  <p>
  <%= cc.label :second_year_spend_bonus %></br>
  <%= cc.number_field :second_year_spend_bonus %>
  </p>
  
  <p>
  <%= cc.label :second_year_spend_requirement %></br>
  <%= cc.number_field :second_year_spend_requirement %>
  </p>
  
  <p>
  <%= cc.label :second_year_time_to_reach_spend_in_months %></br>
  <%= cc.number_field :second_year_time_to_reach_spend_in_months %>
  </p>
  
  <p>
  <%= cc.label :points_per_dollar_spend_general_spend %></br>
  <%= cc.number_field :points_per_dollar_spent_general_spend %>
  </p>
  
  <p>
  <%= cc.label :foreign_transaction_fee %></br>
  <%= cc.number_field :foreign_transaction_fee, :step => 0.1 %>
  </p>
  
  <p>
  <%= cc.label :chip %></br>
  <%= cc.text_field :chip %>
  </p>
  
  <p>
  <%= cc.label :notes %></br>
  <%= cc.text_area :notes %>
  </p>
  
  <p>
  <%= cc.label :business %></br>
  <%= cc.text_field :business %>
  </p>
  
  <p>
  <%= cc.label :personal %></br>
  <%= cc.text_field :personal %>
  </p>
  
  <p>
  <%= cc.label :image_index %></br>
  <%= cc.number_field :image_index %>
  </p>
  
  <p>
  <%= cc.label :url %></br>
  <%= cc.url_field :url %>
  </p>
  
  
  
  <p>
  <%= cc.submit %>
  </p>
  
<% end %>

app/views/creditcards/edit.html.erb
<h1>Tralue - Editing credit card</h1>

<%= form_for :creditcard, url: creditcard_path(@creditcard), method: :patch do |cc| %>

    <% if @creditcard.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@creditcard.errors.count, "error") %> prevented this credit card from being updated:
            </h2>
            <ul>
                <% @creditcard.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <%= render 'form' %>
  
<% end %>

<%= link_to 'Back', creditcards_path, class: 'btn btn-primary' %>

app/views/creditcards/index.html.erb
<h1>Listing credit cards</h1>

<table class="table table-hover">
    <tr>
        <th>Name</th>
        <th>Issuer</th>
    </tr>
    
    <% @creditcards.each do |cc| %>
        <tr>
            <td><%= cc.name %></td>
            <td><%= cc.issuer %></td>
            <td><%= link_to 'Show', creditcard_path(cc), class: 'btn btn-primary' %></td>
            <td><%= link_to 'Edit', edit_creditcard_path(cc), class: 'btn btn-primary' %></td>
            <td><%= link_to 'Destroy', creditcard_path(cc), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
</table>

<%= link_to 'Home', root_path, class: 'btn btn-primary' %>
<%= link_to 'Request to have a card added', new_creditcard_path, class: 'btn btn-primary' %>

app/views/creditcards/new.html.erb
<h1>New credit card</h1>


<%= form_for :creditcard, url: creditcards_path do |cc| %>

  <% if @creditcard.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@creditcard.errors.count, "error") %> prohibited
        this new credit card from being saved:
      </h2>
      <ul>
        <% @creditcard.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'form' %>
  
<% end %>

<%= link_to 'Back', creditcards_path %>

app/views/creditcards/show.html.erb
<h1>Tralue - Show credit card</h1>

<p>
  <strong>Title:</strong>
  <%= @creditcard.name %>
</p>
 
<p>
  <strong>By:</strong>
  <%= @creditcard.issuer %>
</p>

<%= form_for :creditcard, url: creditcard_path(@creditcard) do |cc| %>
  <% if @creditcard.errors.any? %>
    <div id="error explanation">
      <h2>
        <%= pluralize(@creditcard.errors.count, "error") %> prevented this card from being updated:
      </h2>
      <ul>
        <% @creditcard.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>

  <% end %>

<%= render 'form' %>

<% end %>

<%= link_to 'Home', root_path, class: 'btn btn-primary' %>
<%= link_to 'Back', creditcards_path, class: 'btn btn-primary' %>
<%= link_to 'Edit', edit_creditcard_path(@creditcard), class: 'btn btn-primary' %>