config/routes.rb
Myapp::Application.routes.draw do
  get "welcome/index"
  get "home/index"

root to: 'welcome#index'

  resources :trips, :creditcards, :rates, :results

end

app/models/rate.rb
class Rate < ActiveRecord::Base
  #has_and_belongs_to_many :trips
  #as_and_belongs_to_many :creditcards
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  http_basic_authenticate_with name: "shunter", password: "derpderp", except: [:index]
  
  def index
    @rates = Rate.all
  end
  
  def show
    @rate = Rate.find(params[:id])
  end
  
  def new
    @rate = Rate.new
  end
  
  def edit
    @rate = Rate.find(params[:id])
  end
  
  def create
    @rate = Rate.create(transfer_rate_check) #bleh
    
    if @rate.save
      redirect_to @rate
    else
      render 'new'
    end
    
  end
  
  def update 
    @rate = Rate.find(params[:id])
    
    if @rate.update(transfer_rate_check)
      redirect_to @rate
    else
      render 'edit'
    end
    
  end
  
  def destroy
    @rate = Rate.find(params[:id])
    @rate.destroy
    
    redirect_to rates_path
  end
  
  private
    #require all new entries to have these four fields, at a minimum, INCLUDING notes
    def transfer_rate_check
      params.require(:rate).permit(:transferringprogram,
                                           :transfereeprogram,
                                           :transferratio,
                                           :transfernotes)
    end
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/rates/_form.html.erb
<%= form_for @rate do |tr| %>
  <% if @rate.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@rate.errors.count, "error") %> prohibited this credit card from being saved:
      </h2>
      <ul>
        <% @rate.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
  <%= tr.label :transferringprogram %></br>
  <%= tr.text_field :transferringprogram %>
  </p>
  
  <p>
  <%= tr.label :transfereeprogram %></br>
  <%= tr.text_field :transfereeprogram %>
  </p>
  
  <p>
  <%= tr.label :transferratio %></br>
  <%= tr.text_field :transferratio %>
  </p>
  
  <p>
  <%= tr.label :transfernotes %></br>
  <%= tr.text_field :transfernotes %>
  </p>
  
  <p>
  <%= tr.submit %>
  </p>
  
<% end %>

app/views/rates/edit.html.erb
<h1>Tralue - Editing transfer rate</h1>

<%= form_for :rate, url: rate_path(@rate), method: :patch do |tr| %>

    <% if @rate.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@rate.errors.count, "error") %> prevented this credit card from being updated:
            </h2>
            <ul>
                <% @rate.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <%= render 'form' %>
  
<% end %>

<%= link_to 'Back', rates_path, class: 'btn btn-primary' %>

app/views/rates/index.html.erb
<h1>Listing transfer rates</h1>

<table class="table table-hover">
    <tr>
        <th>Transferring program</th>
        <th>Transferee program</th>
        <th>Transfer ratio</th>
        <th>Transfer notes</th>
    </tr>
    
    <% @rates.each do |tr| %>
        <tr>
            <td><%= tr.transferringprogram %></td>
            <td><%= tr.transfereeprogram %></td>
            <td><%= tr.transferratio %></td>
            <td><%= tr.transfernotes %></td>
            <td><%= link_to 'Show', rate_path(tr), class: 'btn btn-primary' %></td>
            <td><%= link_to 'Edit', edit_rate_path(tr), class: 'btn btn-primary' %></td>
            <td><%= link_to 'Destroy', rate_path(tr), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
</table>

<%= link_to 'Home', root_path, class: 'btn btn-primary' %>

app/views/rates/new.html.erb
<h1>New transfer rate</h1>

<%= @transferrate %>
<%= form_for :rate, url: rates_path do |tr| %>

  <% if @rate.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@rate.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @rate.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'form' %>
  
<% end %>

<%= link_to 'Back', rates_path %>

app/views/rates/show.html.erb
<h1>Tralue</h1>

<p>
  <strong>Transferring program:</strong>
  <%= @rate.transferringprogram %>
</p>
 
<p>
  <strong>Transferee program:</strong>
  <%= @rate.transfereeprogram %>
</p>

<p>
  <strong>Ratio:</strong>
  <%= @rate.transferratio %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @rate.transfernotes %>
</p>

<%= link_to 'Back', rates_path, class: 'btn btn-primary' %>
<%= link_to 'Edit', edit_rate_path(@rate), class: 'btn btn-primary' %>